apiVersion: apps/v1
kind: Deployment
metadata:
  name: swtcproxy
  labels:
    app: swtcproxy
    chain: swtc
spec:
  selector:
    matchLabels:
      app: swtcproxy
  replicas: 3
  template:
    metadata:
      labels:
        app: swtcproxy
        chain: swtc
    spec:
      containers:
      - name: swtcproxy
        image: lospringliu/swtcproxy:latest
        ports:
        - containerPort: 5080
        env:
        - name: UPSTREAM
          value: "ws://swtcproxy.swtclib.ca:5020"
        - name: DEBUG
          value: "true"
        - name: RATE
          value: "300"
  
---

apiVersion: v1
kind: Service
metadata:
  name: service-swtcproxy
spec:
  selector:
    app: swtcproxy
    chain: swtc
  ports:
    - protocol: TCP
      port: 5080
      targetPort: 5080
